# Generated by Django 4.0.3 on 2022-04-12 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Peserta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.TextField()),
                ('NIP', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Soal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta', models.TextField()),
                ('ellecion_uno', models.TextField()),
                ('ellecion_dos', models.TextField()),
                ('ellecion_tres', models.TextField()),
                ('ellecion_cuatro', models.TextField()),
                ('larespuesta', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Jawabanpeserta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('jawaban', models.TextField()),
                ('nama', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admindepaginas.peserta')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admindepaginas.soal')),
            ],
        ),
    ]
