# Generated by Django 4.0.3 on 2022-04-15 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admindepaginas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jawabanpeserta',
            name='nama',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='jawabanpeserta',
            name='pregunta',
            field=models.TextField(),
        ),
    ]
