# Generated by Django 4.0.3 on 2022-04-15 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admindepaginas', '0002_alter_jawabanpeserta_nama_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jawabanpeserta',
            name='larespuesta',
            field=models.CharField(max_length=1, null=True),
        ),
    ]
