# Generated by Django 4.0.3 on 2022-04-15 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admindepaginas', '0003_jawabanpeserta_larespuesta'),
    ]

    operations = [
        migrations.AddField(
            model_name='jawabanpeserta',
            name='score1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='jawabanpeserta',
            name='score2',
            field=models.IntegerField(default=0),
        ),
    ]
