# Generated by Django 4.0.4 on 2022-04-27 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admindepaginas', '0006_remove_soal_ideh_jawabanpeserta_ideh'),
    ]

    operations = [
        migrations.AddField(
            model_name='jawabanpeserta',
            name='is_true',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='jawabanpeserta',
            name='jawaban',
            field=models.CharField(max_length=1),
        ),
    ]
